# A generic, single database configuration.

[alembic]
# Path to migration scripts (relative to this file)
script_location = alembic

# Alembic reads this value but our env.py overrides it from .env
sqlalchemy.url = postgresql+psycopg2://placeholder/placeholder

# Length of revision IDs
revision_environment = false


[post_write_hooks]
# Uncomment to auto-format generated migration files
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 88 REVISION_SCRIPT_FILENAME


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
