# Generic Mako template — do not edit (managed by Alembic)
"""add is_deleted to user

Revision ID: 8b01d103d59c
Revises: 06d25922f952
Create Date: 2026-05-06 23:26:18.997492

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b01d103d59c'
down_revision: Union[str, None] = '06d25922f952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'zone')
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.add_column('tasks', sa.Column('zone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
