# Generic Mako template — do not edit (managed by Alembic)
"""add_total_required_qty_to_materials

Revision ID: b8fc9d7ab3fe
Revises: ed53b63939d0
Create Date: 2026-05-13 23:32:59.653515

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fc9d7ab3fe'
down_revision: Union[str, None] = 'ed53b63939d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('total_required_qty', sa.Numeric(precision=14, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'total_required_qty')
    # ### end Alembic commands ###
