# Generic Mako template — do not edit (managed by Alembic)
"""Make Attendance.project_id nullable and set null on delete

Revision ID: c6a68a607bc5
Revises: b8fc9d7ab3fe
Create Date: 2026-05-14 22:43:16.068220

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a68a607bc5'
down_revision: Union[str, None] = 'b8fc9d7ab3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('attendance_project_id_fkey', 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_project_id_fkey', 'attendance', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('attendance', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
