# Generic Mako template — do not edit (managed by Alembic)
"""add_completion_category_and_fix_site_photos_constraint

Revision ID: ed53b63939d0
Revises: 8b01d103d59c
Create Date: 2026-05-09 23:54:40.660712

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed53b63939d0'
down_revision: Union[str, None] = '8b01d103d59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
